# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: docker pull neo4j/neo4j-arm64-experimental:4.1-arm64 # runs during prebuild
    command: |
      docker run  -d \
      -p 7474:7474 --publish=7687:7687 \
      --volume=$HOME/neo4j/data:/data \
      neo4j/neo4j:54c6d1132460
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 7474
    onOpen: open-browser
    visibility: public
  - port: 7687
    visibility: public
    onOpen: ignore
    
